src/Entity/Categories.php
<?php

namespace App\Entity;

use App\Repository\CategoriesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoriesRepository::class)
 * @ORM\Table(name="categories")
 */
class Categories {

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer", name="cat_id")
     */
    private $cat_id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $cat_libelle;

    /**
     * @ORM\Column(type="integer")
     */
    private $cat_upper_cat;

    /**
     * @ORM\OneToMany(targetEntity=Products::class, mappedBy="category")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getCatId(): ?int {
        return $this->cat_id;
    }

    public function setCatId(int $cat_id): self {
        $this->cat_id = $cat_id;

        return $this;
    }

    public function getCatLibelle(): ?string {
        return $this->cat_libelle;
    }

    public function setCatLibelle(string $cat_libelle): self {
        $this->cat_libelle = $cat_libelle;

        return $this;
    }

    public function getCatUpperCat(): ?int {
        return $this->cat_upper_cat;
    }

    public function setCatUpperCat(int $cat_upper_cat): self {
        $this->cat_upper_cat = $cat_upper_cat;

        return $this;
    }

    /**
     * @return Collection|Products[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Products $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Products $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }
    // Fonction pour récupérer une catégorie sous forme de chaîne de caractère
    public function __toString()
    {
        return $this->cat_libelle;
    }

}

src/Entity/Commentary.php
<?php

namespace App\Entity;

use App\Repository\CommentaryRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentaryRepository::class)
 */
class Commentary
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer", name="comm_id")
     */
    private $comm_id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $comm_comment;

    /**
     * @ORM\Column(type="integer")
     */
    private $comm_note;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commentaries")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="user_id")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Products::class, inversedBy="commentaries")
     * @ORM\JoinColumn(name="product_id", referencedColumnName="prod_id")
     */
    private $product;

    public function getCommId(): ?int
    {
        return $this->comm_id;
    }

    public function getCommComment(): ?string
    {
        return $this->comm_comment;
    }

    public function setCommComment(string $comm_comment): self
    {
        $this->comm_comment = $comm_comment;

        return $this;
    }

    public function getCommNote(): ?int
    {
        return $this->comm_note;
    }

    public function setCommNote(int $comm_note): self
    {
        $this->comm_note = $comm_note;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getProduct(): ?Products
    {
        return $this->product;
    }

    public function setProduct(?Products $product): self
    {
        $this->product = $product;

        return $this;
    }
}

src/Entity/Group.php
<?php

namespace App\Entity;

use App\Repository\GroupRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GroupRepository::class)
 * @ORM\Table(name="`group`")
 */
class Group
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer", name="group_id")
     */
    private $group_id;

    

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $group_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $group_descr;

    /**
     * @ORM\OneToMany(targetEntity=Products::class, mappedBy="groupe")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getGroupId(): ?int
    {
        return $this->group_id;
    }

    

    public function getGroupName(): ?string
    {
        return $this->group_name;
    }

    public function setGroupName(string $group_name): self
    {
        $this->group_name = $group_name;

        return $this;
    }

    public function getGroupDescr(): ?string
    {
        return $this->group_descr;
    }

    public function setGroupDescr(string $group_descr): self
    {
        $this->group_descr = $group_descr;

        return $this;
    }

    /**
     * @return Collection|Products[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Products $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setGroupe($this);
        }

        return $this;
    }

    public function removeProduct(Products $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getGroupe() === $this) {
                $product->setGroupe(null);
            }
        }

        return $this;
    }
}

src/Entity/Photo.php
<?php

namespace App\Entity;

use App\Repository\PhotoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PhotoRepository::class)
 * @ORM\Table(name="photo")
 */
class Photo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer", name="photo_id")
     */
    private $photo_id;

    /**
     * @ORM\Column(type="string", length=6)
     */
    private $photo_format;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    private $photo_descr;

    /**
     * @ORM\OneToMany(targetEntity=Products::class, mappedBy="photo")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getPhotoId(): ?int
    {
        return $this->photo_id;
    }

    public function getPhotoFormat(): ?string
    {
        return $this->photo_format;
    }

    public function setPhotoFormat(string $photo_format): self
    {
        $this->photo_format = $photo_format;

        return $this;
    }

    public function getPhotoDescr(): ?string
    {
        return $this->photo_descr;
    }

    public function setPhotoDescr(?string $photo_descr): self
    {
        $this->photo_descr = $photo_descr;

        return $this;
    }

    /**
     * @return Collection|Products[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Products $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setPhoto($this);
        }

        return $this;
    }

    public function removeProduct(Products $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getPhoto() === $this) {
                $product->setPhoto(null);
            }
        }

        return $this;
    }
}

src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductsRepository::class)
 * @ORM\Table(name="Products")
 */
class Products {

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer", name="prod_id")
     */
    private $prod_id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prod_name;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    private $prod_descr;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2)
     */
    private $prod_price;

    /**
     * @ORM\Column(type="boolean")
     */
    private $prod_display;

    /**
     * @ORM\Column(type="integer")
     */
    private $prod_stock;

    /**
     * @ORM\OneToMany(targetEntity=Commentary::class, mappedBy="product")
     */
    private $commentaries;

    /**
     * @ORM\ManyToOne(targetEntity=Group::class, inversedBy="products")
     * @ORM\JoinColumn(name="group_id", referencedColumnName="group_id")
     */
    private $group;

    /**
     * @ORM\ManyToOne(targetEntity=Categories::class, inversedBy="products")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="cat_id")
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity="Promotions")
     * @ORM\JoinTable(name="promo_products",
     *      joinColumns={@ORM\JoinColumn(name="product_id", referencedColumnName="prod_id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="promo_id", referencedColumnName="promo_id")}
     *      )
     */
    private $promotions;

    /**
     * @ORM\OneToMany(targetEntity=Cart::class, mappedBy="products")
     */
    private $carts;

    /**
     * @ORM\OneToMany(targetEntity=ProductsOrder::class, mappedBy="products")
     */
    private $productsOrders;

    /**
     * @ORM\ManyToOne(targetEntity=Label::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false, name="label_siren", referencedColumnName="label_siren")
     */
    private $label;

    /**
     * @ORM\ManyToOne(targetEntity=Photo::class, inversedBy="products")
     * @ORM\JoinColumn(name="photo_id", referencedColumnName="photo_id")
     */
    private $photo;

    /**
     * @ORM\ManyToOne(targetEntity=Provider::class, inversedBy="products")
     * @ORM\JoinColumn(name="provider_siren", referencedColumnName="prov_siren")
     */
    private $provider;

    public function __construct() {
        $this->commentaries = new ArrayCollection();
        $this->promotions = new ArrayCollection();
        $this->carts = new ArrayCollection();
        $this->productsOrders = new ArrayCollection();
    }

    public function getId(): ?int {
        return $this->prod_id;
    }

    public function getProdName(): ?string {
        return $this->prod_name;
    }

    public function setProdName(string $prod_name): self {
        $this->prod_name = $prod_name;

        return $this;
    }

    public function getProdDescr(): ?string {
        return $this->prod_descr;
    }

    public function setProdDescr(?string $prod_descr): self {
        $this->prod_descr = $prod_descr;

        return $this;
    }

    public function getProdPrice(): ?string {
        return $this->prod_price;
    }

    public function setProdPrice(string $prod_price): self {
        $this->prod_price = $prod_price;

        return $this;
    }

    public function getProdDisplay(): ?bool {
        return $this->prod_display;
    }

    public function setProdDisplay(bool $prod_display): self {
        $this->prod_display = $prod_display;

        return $this;
    }

    public function getProdStock(): ?int {
        return $this->prod_stock;
    }

    public function setProdStock(int $prod_stock): self {
        $this->prod_stock = $prod_stock;

        return $this;
    }

    /**
     * @return Collection|Commentary[]
     */
    public function getCommentaries(): Collection {
        return $this->commentaries;
    }

    public function addCommentary(Commentary $commentary): self {
        if (!$this->commentaries->contains($commentary)) {
            $this->commentaries[] = $commentary;
            $commentary->setProduct($this);
        }

        return $this;
    }

    public function removeCommentary(Commentary $commentary): self {
        if ($this->commentaries->contains($commentary)) {
            $this->commentaries->removeElement($commentary);
            // set the owning side to null (unless already changed)
            if ($commentary->getProduct() === $this) {
                $commentary->setProduct(null);
            }
        }

        return $this;
    }

    public function getGroup(): ?Group {
        return $this->group;
    }

    public function setGroup(?Group $group): self {
        $this->group = $group;

        return $this;
    }

    public function getPromotions(): ArrayCollection {
        return $this->promotions;
    }

    public function setPromotions(?Promotions $promotions): self {
        $this->promotions = $promotions;

        return $this;
    }

    public function getCategory(): ?Categories {
        return $this->category;
    }

    public function setCategory(?Categories $category): self {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Cart[]
     */
    public function getCarts(): Collection {
        return $this->carts;
    }

    public function addCart(Cart $cart): self {
        if (!$this->carts->contains($cart)) {
            $this->carts[] = $cart;
            $cart->setProducts($this);
        }

        return $this;
    }

    public function removeCart(Cart $cart): self {
        if ($this->carts->contains($cart)) {
            $this->carts->removeElement($cart);
            // set the owning side to null (unless already changed)
            if ($cart->getProducts() === $this) {
                $cart->setProducts(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ProductsOrder[]
     */
    public function getProductsOrders(): Collection {
        return $this->productsOrders;
    }

    public function addProductsOrder(ProductsOrder $productsOrder): self {
        if (!$this->productsOrders->contains($productsOrder)) {
            $this->productsOrders[] = $productsOrder;
            $productsOrder->setProducts($this);
        }

        return $this;
    }

    public function removeProductsOrder(ProductsOrder $productsOrder): self {
        if ($this->productsOrders->contains($productsOrder)) {
            $this->productsOrders->removeElement($productsOrder);
            // set the owning side to null (unless already changed)
            if ($productsOrder->getProducts() === $this) {
                $productsOrder->setProducts(null);
            }
        }

        return $this;
    }

    public function getLabel(): ?Label {
        return $this->label;
    }

    public function setLabel(?Label $label): self {
        $this->label = $label;

        return $this;
    }

    public function getPhoto(): ?Photo
    {
        return $this->photo;
    }

    public function setPhoto(?Photo $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getProvider(): ?Provider
    {
        return $this->provider;
    }

    public function setProvider(?Provider $provider): self
    {
        $this->provider = $provider;

        return $this;
    }

}

src/Form/ProductsType.php
<?php

namespace App\Form;

use App\Entity\Products;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('prod_name', null, ['label'=>'nom'])
            ->add('prod_descr', TextareaType::class, ['label'=>'description', 'attr'=> ['class'=>'tinymce']])
            ->add('prod_price', null, ['label'=>'prix'])
            ->add('prod_display', null, ['label'=>'afficher le produit'])
            ->add('prod_stock', null, ['label'=>'en stock'])
            ->add('group', null, ['label'=>'groupe'])
            ->add('category', null, ['label'=>'categorie'])
            ->add('label', null, ['label'=>'label'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Products::class,
        ]);
    }
    
}

templates/products/_card.html.twig
<div class="col-12 col-lg-6 p-1">
    <div class="card mb-3 mr-3">
        {% if product.prodDisplay == 1 %}
        <div class="row no-gutters align-items-center p-2">
            <div class="col-12 col-md-4">
                <img src="{{ asset('images/vinylfilrouge/' ~ product.Photo.photoId ~ '.' ~ product.Photo.photoFormat)}}"
                    class="cover">
            </div>
            <div class="col">
                <div class="card-body">
                    <h3 class="card-title font-weight-bold">{{ product.prodName }}</h3>
                    <div class="mb-3 font-weight-bold">Prix HT : {{ product.prodPrice }}€</div>
                    <p class="card-text">
                    <div class="mb-2">Groupe : {{ product.group.groupName }}</div>
                     <div>Genre : {{ product.category.catLibelle }}</div>
                    <div class="mb-3">{{ product.prodDescr }}</div>

                    {% if product.prodStock == 0 %}
                    <div>Produit Indisponible</div>
                    {% else %}
                    <div>Quantité disponible : {{ product.prodStock }}</div>
                    {% endif %}
                    </p>
                    <div>
                        <a href="{{ path('products_show', {'prod_id': product.getId()}) }}"><i
                                class="fas fa-eye"></i></a>&nbsp;&nbsp;
                        {% if product.prodStock == 0 %}

                        {% else %}
                        <a href="{{ path('cart_add', {'id' : product.getId()}) }}"><i class="fas fa-cart-plus"></i></a>
                        {% endif %}
                    </div>
                    {% else %}
                    {% endif %}


                </div>
            </div>
        </div>
    </div>
</div>

templates/products/_delete_form.html.twig
<form method="post" action="{{ path('products_delete', {'prod_id': product.getId()}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.getId()) }}">
    <button class="btn">Delete</button>
</form>

templates/products/_filter.html.twig
{{ form_start(form, {attr: {class: 'filter'}}) }}

{{ form_row(form.q) }}
<h4>Catégories</h4>
{{ form_row(form.categories) }}
<h4>Prix</h4>
<div class="row">
    <div class="col-md-6">
        {{ form_row(form.min) }}
    </div>
    <div class="col-md-6">
        {{ form_row(form.max) }}
    </div>
</div>
<h4>Promotions</h4>
{{ form_row(form.promo) }}
    <button type="submit" class="btn btn-primary w-100">Filtrer</button>
{{ form_end(form) }}

templates/products/_form.html.twig
<div class="container mt-4">
    {{ form_start(form) }}
    <div class="row">
        <div class="col-md-5">{{ form_row(form.prod_name) }}</div>
        <div class="col-md-2">{{ form_row(form.prod_price) }}</div>
        <div class="col-md-2">{{ form_row(form.prod_stock) }}</div>
        <div class="col-md-3">{{ form_row(form.prod_display) }}</div>   
    </div>
    <div class="row">
        <div class="col-md-12">{{ form_row(form.prod_descr) }}</div>
    </div>
    <div class="row">
        <div class="col-md-6">{{ form_row(form.group) }}</div>
        <div class="col-md-6">{{ form_row(form.category) }}</div>
        <div class="col-md-6">{{ form_row(form.label) }}</div>
    </div>
   
    <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
</div>

templates/products/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Products{% endblock %}

{% block body %}
    <h1>Edit Products</h1>

    {{ include('products/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('products_index') }}">back to list</a>

    {{ include('products/_delete_form.html.twig') }}
{% endblock %}

templates/products/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Products index{% endblock %}

{% block body %}
<h1 class="m-5">Vinyles</h1>

<div class="row">
    <div class="col-md-3">
        {% include 'products/_filter.html.twig' with {form:form} only %}
    </div>
    <div class="col-md-9">

        <div class="row no-gutters">
            {% for product in products %}
            {# include de card produit à laquelle on passe une liste de produits #}
            {% include 'products/_card.html.twig' with {product : product } only %}
            {% endfor %}
        </div>
    </div>
</div>

{# display navigation #}
<div class="navigation align-items-center">
     {{ knp_pagination_render(products) }} 
</div>










{% endblock %}

templates/products/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Products{% endblock %}

{% block body %}
    <h1>Create new Products</h1>

    {{ include('products/_form.html.twig') }}

    <a href="{{ path('products_index') }}">back to list</a>
{% endblock %}

templates/products/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Products{% endblock %}

{% block body %}
    <h1>Products</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Photo</th>
                <td><img src="{{ asset('images/vinylfilrouge/' ~ product.Photo.photoId ~ '.' ~ product.Photo.photoFormat)}}" class="cover"></td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ product.prodName }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ product.prodDescr }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ product.prodPrice }}</td>
            </tr>
            <tr>
                <th>Stock restant</th>
                <td>{{ product.prodStock }}</td>
            </tr>
        </tbody>
    </table>
<hr>
    <table class="table">
        <legend>Avis des clients</legend>
        <thead>
                <tr>
                    <th>Note</th>
                    <th>Commentaire</th>
                </tr>
        </thead>
        <tbody>
        {% for commentary in product.getCommentaries() %}
        <tr>
            <td> {{ commentary.commNote }}</td>
            <td>{{ commentary.commComment }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('products') }}">back to list</a>



{% endblock %}