src/Entity/Group.php
<?php

namespace App\Entity;

use App\Repository\GroupRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GroupRepository::class)
 * @ORM\Table(name="`group`")
 */
class Group
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer", name="group_id")
     */
    private $group_id;

    

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $group_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $group_descr;

    /**
     * @ORM\OneToMany(targetEntity=Products::class, mappedBy="groupe")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getGroupId(): ?int
    {
        return $this->group_id;
    }

    

    public function getGroupName(): ?string
    {
        return $this->group_name;
    }

    public function setGroupName(string $group_name): self
    {
        $this->group_name = $group_name;

        return $this;
    }

    public function getGroupDescr(): ?string
    {
        return $this->group_descr;
    }

    public function setGroupDescr(string $group_descr): self
    {
        $this->group_descr = $group_descr;

        return $this;
    }

    /**
     * @return Collection|Products[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Products $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setGroupe($this);
        }

        return $this;
    }

    public function removeProduct(Products $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getGroupe() === $this) {
                $product->setGroupe(null);
            }
        }

        return $this;
    }
}

src/Form/GroupType.php
<?php

namespace App\Form;

use App\Entity\Group;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GroupType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('group_name')
            ->add('group_descr')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Group::class,
        ]);
    }
}

src/Controller/GroupController.php
<?php

namespace App\Controller;

use App\Entity\Group;
use App\Form\GroupType;
use App\Repository\GroupRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/groups")
 */
class GroupController extends AbstractController
{
    /**
     * @Route("/", name="group_index", methods={"GET"})
     */
    public function index(GroupRepository $groupRepository): Response
    {
        return $this->render('group/index.html.twig', [
            'groups' => $groupRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="group_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $group = new Group();
        $form = $this->createForm(GroupType::class, $group);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($group);
            $entityManager->flush();

            return $this->redirectToRoute('group_index');
        }

        return $this->render('group/new.html.twig', [
            'group' => $group,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{group_id}", name="group_show", methods={"GET"})
     */
    public function show(Group $group): Response
    {
        return $this->render('group/show.html.twig', [
            'group' => $group,
        ]);
    }

    /**
     * @Route("/{group_id}/edit", name="group_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Group $group): Response
    {
        $form = $this->createForm(GroupType::class, $group);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('group_index');
        }

        return $this->render('group/edit.html.twig', [
            'group' => $group,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{group_id}", name="group_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Group $group): Response
    {
        if ($this->isCsrfTokenValid('delete'.$group->getGroup_id(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($group);
            $entityManager->flush();
        }

        return $this->redirectToRoute('group_index');
    }
}

templates/group/_delete_form.html.twig
<form method="post" action="{{ path('group_delete', {'group_id': group.group_id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ group.group_id) }}">
    <button class="btn">Delete</button>
</form>

templates/group/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/group/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Group{% endblock %}

{% block body %}
    <h1>Edit Group</h1>

    {{ include('group/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('group_index') }}">back to list</a>

    {{ include('group/_delete_form.html.twig') }}
{% endblock %}

templates/group/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Group index{% endblock %}

{% block body %}
    <h1>Liste des groupes</h1>

    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Description</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for group in groups %}
            <tr>
                <td>{{ group.groupId }}</td>
                <td>{{ group.groupName }}</td>
                <td>{{ group.groupDescr }}</td>
                <td>
                    <a href="{{ path('group_show', {'group_id': group.group_id}) }}"><i class="fas fa-eye"></i></a>&nbsp;&nbsp;
                    <a href="{{ path('group_edit', {'group_id': group.group_id}) }}"><i class="fas fa-edit"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('group_new') }}">Create new</a>
{% endblock %}

templates/group/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Group{% endblock %}

{% block body %}
    <h1>Create new Group</h1>

    {{ include('group/_form.html.twig') }}

    <a href="{{ path('group_index') }}">back to list</a>
{% endblock %}

templates/group/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Group{% endblock %}

{% block body %}
    <h1>Group</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Group_id</th>
                <td>{{ group.groupId }}</td>
            </tr>
            <tr>
                <th>Group_name</th>
                <td>{{ group.groupName }}</td>
            </tr>
            <tr>
                <th>Group_descr</th>
                <td>{{ group.groupDescr }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('group_index') }}">back to list</a>

    <a href="{{ path('group_edit', {'group_id': group.group_id}) }}">edit</a>

    {{ include('group/_delete_form.html.twig') }}
{% endblock %}