src/Entity/Promotions.php
<?php

namespace App\Entity;

use App\Repository\PromotionsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PromotionsRepository::class)
 * @ORM\Table(name="promotions")
 */
class Promotions
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer", name="promo_id")
     */
    private $promo_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $promo_percent;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $promo_libelle;

    /**
     * @ORM\Column(type="boolean")
     */
    private $promo_active;

    /**
     * @ORM\Column(type="datetime")
     */
    private $promo_date_fin;

    /**
     * @ORM\ManyToOne(targetEntity=TypePromo::class, inversedBy="promotions")
     * @ORM\JoinColumn(name="type_promo_id", referencedColumnName="type_promo_id")
     */
    private $type_promo;

    public function getPromoId(): ?int
    {
        return $this->promo_id;
    }

    public function setPromoId(int $promo_id): self
    {
        $this->promo_id = $promo_id;

        return $this;
    }

    public function getPromoPercent(): ?int
    {
        return $this->promo_percent;
    }

    public function setPromoPercent(int $promo_percent): self
    {
        $this->promo_percent = $promo_percent;

        return $this;
    }

    public function getPromoLibelle(): ?string
    {
        return $this->promo_libelle;
    }

    public function setPromoLibelle(string $promo_libelle): self
    {
        $this->promo_libelle = $promo_libelle;

        return $this;
    }

    public function getPromoActive(): ?bool
    {
        return $this->promo_active;
    }

    public function setPromoActive(bool $promo_active): self
    {
        $this->promo_active = $promo_active;

        return $this;
    }

    public function getPromoDateFin(): ?\DateTimeInterface
    {
        return $this->promo_date_fin;
    }

    public function setPromoDateFin(\DateTimeInterface $promo_date_fin): self
    {
        $this->promo_date_fin = $promo_date_fin;

        return $this;
    }

    public function getTypePromo(): ?TypePromo
    {
        return $this->type_promo;
    }

    public function setTypePromo(?TypePromo $type_promo): self
    {
        $this->type_promo = $type_promo;

        return $this;
    }
}

src/Form/PromotionsType.php
<?php

namespace App\Form;

use App\Entity\Promotions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PromotionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('promo_percent')
            ->add('promo_libelle')
            ->add('promo_active')
            ->add('promo_date_fin')
            ->add('type_promo')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Promotions::class,
        ]);
    }
}

src/Controller/PromotionsController.php
<?php

namespace App\Controller;

use App\Entity\Promotions;
use App\Form\PromotionsType;
use App\Repository\PromotionsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/promotions")
 */
class PromotionsController extends AbstractController
{
    /**
     * @Route("/", name="promotions_index", methods={"GET"})
     */
    public function index(PromotionsRepository $promotionsRepository): Response
    {
        return $this->render('promotions/index.html.twig', [
            'promotions' => $promotionsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="promotions_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $promotion = new Promotions();
        $form = $this->createForm(PromotionsType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($promotion);
            $entityManager->flush();

            return $this->redirectToRoute('promotions_index');
        }

        return $this->render('promotions/new.html.twig', [
            'promotion' => $promotion,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{promo_id}", name="promotions_show", methods={"GET"})
     */
    public function show(Promotions $promotion): Response
    {
        return $this->render('promotions/show.html.twig', [
            'promotion' => $promotion,
        ]);
    }

    /**
     * @Route("/{promo_id}/edit", name="promotions_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Promotions $promotion): Response
    {
        $form = $this->createForm(PromotionsType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('promotions_index');
        }

        return $this->render('promotions/edit.html.twig', [
            'promotion' => $promotion,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{promo_id}", name="promotions_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Promotions $promotion): Response
    {
        if ($this->isCsrfTokenValid('delete'.$promotion->getPromo_id(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($promotion);
            $entityManager->flush();
        }

        return $this->redirectToRoute('promotions_index');
    }
}

templates/promotions/_delete_form.html.twig
<form method="post" action="{{ path('promotions_delete', {'promo_id': promotion.promo_id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ promotion.promo_id) }}">
    <button class="btn">Delete</button>
</form>

templates/promotions/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/promotions/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Promotions{% endblock %}

{% block body %}
    <h1>Edit Promotions</h1>

    {{ include('promotions/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('promotions_index') }}">back to list</a>

    {{ include('promotions/_delete_form.html.twig') }}
{% endblock %}

templates/promotions/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promotions index{% endblock %}

{% block body %}
    <h1>Liste des promotions</h1>

    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Pourcentage</th>
                <th>Libellé</th>
                <th>Actif ?</th>
                <th>Date de fin</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for promotion in promotions %}
            <tr>
                <td>{{ promotion.promoId }}</td>
                <td>{{ promotion.promoPercent }}</td>
                <td>{{ promotion.promoLibelle }}</td>
                <td>{{ promotion.promoActive ? 'Oui' : 'Non' }}</td>
                <td>{{ promotion.promoDateFin ? promotion.promoDateFin|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('promotions_show', {'promo_id': promotion.promo_id}) }}"><i class="fas fa-eye"></i></a>&nbsp;&nbsp;
                    <a href="{{ path('promotions_edit', {'promo_id': promotion.promo_id}) }}"><i class="fas fa-edit"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('promotions_new') }}">Create new</a>
{% endblock %}

templates/promotions/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Promotions{% endblock %}

{% block body %}
    <h1>Create new Promotions</h1>

    {{ include('promotions/_form.html.twig') }}

    <a href="{{ path('promotions_index') }}">back to list</a>
{% endblock %}

templates/promotions/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promotions{% endblock %}

{% block body %}
    <h1>Promotions</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Promo_id</th>
                <td>{{ promotion.promoId }}</td>
            </tr>
            <tr>
                <th>Promo_percent</th>
                <td>{{ promotion.promoPercent }}</td>
            </tr>
            <tr>
                <th>Promo_libelle</th>
                <td>{{ promotion.promoLibelle }}</td>
            </tr>
            <tr>
                <th>Promo_active</th>
                <td>{{ promotion.promoActive ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Promo_date_fin</th>
                <td>{{ promotion.promoDateFin ? promotion.promoDateFin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('promotions_index') }}">back to list</a>

    <a href="{{ path('promotions_edit', {'promo_id': promotion.promo_id}) }}">edit</a>

    {{ include('promotions/_delete_form.html.twig') }}
{% endblock %}