src/Entity/Provider.php
<?php

namespace App\Entity;

use App\Repository\ProviderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProviderRepository::class)
 */
class Provider {

    /**
     * @ORM\Id()
     * @ORM\Column(type="string", length=9)
     */
    private $prov_siren;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $prov_name;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $prov_mail;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $prov_phone;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $prov_descr;

    /**
     * @ORM\ManyToOne(targetEntity=TypeProvider::class, inversedBy="providers")
     * @ORM\JoinColumn(name="type_provider_id", referencedColumnName="type_prov_id")
     */
    private $type_provider;

    /**
     * @ORM\OneToMany(targetEntity=Products::class, mappedBy="provider")
     */
    private $products;

    /**
     * @ORM\ManyToOne(targetEntity=Address::class, inversedBy="providers")
     * @ORM\JoinColumn(name="address_id", referencedColumnName="address_id")
     */
    private $address;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getProvSiren(): ?string {
        return $this->prov_siren;
    }

    public function setProvSiren(string $prov_siren): self {
        $this->prov_siren = $prov_siren;

        return $this;
    }

    public function getProvName(): ?string {
        return $this->prov_name;
    }

    public function setProvName(string $prov_name): self {
        $this->prov_name = $prov_name;

        return $this;
    }

    public function getProvMail(): ?string {
        return $this->prov_mail;
    }

    public function setProvMail(string $prov_mail): self {
        $this->prov_mail = $prov_mail;

        return $this;
    }

    public function getProvPhone(): ?string {
        return $this->prov_phone;
    }

    public function setProvPhone(string $prov_phone): self {
        $this->prov_phone = $prov_phone;

        return $this;
    }

    public function getProvDescr(): ?string {
        return $this->prov_descr;
    }

    public function setProvDescr(string $prov_descr): self {
        $this->prov_descr = $prov_descr;

        return $this;
    }

    public function getTypeProvider(): ?TypeProvider
    {
        return $this->type_provider;
    }

    public function setTypeProvider(?TypeProvider $type_provider): self
    {
        $this->type_provider = $type_provider;

        return $this;
    }

    /**
     * @return Collection|Products[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Products $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setProvider($this);
        }

        return $this;
    }

    public function removeProduct(Products $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getProvider() === $this) {
                $product->setProvider(null);
            }
        }

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(?Address $address): self
    {
        $this->address = $address;

        return $this;
    }

}

src/Form/ProviderType.php
<?php

namespace App\Form;

use App\Entity\Provider;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProviderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('prov_siren')
            ->add('prov_name')
            ->add('prov_mail')
            ->add('prov_phone')
            ->add('prov_descr')
            ->add('type_provider')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Provider::class,
        ]);
    }
}

src/Controller/ProviderController.php
<?php

namespace App\Controller;

use App\Entity\Provider;
use App\Form\ProviderType;
use App\Repository\ProviderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/providers")
 */
class ProviderController extends AbstractController
{
    /**
     * @Route("/", name="provider_index", methods={"GET"})
     */
    public function index(ProviderRepository $providerRepository): Response
    {
        return $this->render('provider/index.html.twig', [
            'providers' => $providerRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="provider_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $provider = new Provider();
        $form = $this->createForm(ProviderType::class, $provider);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($provider);
            $entityManager->flush();

            return $this->redirectToRoute('provider_index');
        }

        return $this->render('provider/new.html.twig', [
            'provider' => $provider,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{prov_siren}", name="provider_show", methods={"GET"})
     */
    public function show(Provider $provider): Response
    {
        return $this->render('provider/show.html.twig', [
            'provider' => $provider,
        ]);
    }

    /**
     * @Route("/{prov_siren}/edit", name="provider_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Provider $provider): Response
    {
        $form = $this->createForm(ProviderType::class, $provider);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('provider_index');
        }

        return $this->render('provider/edit.html.twig', [
            'provider' => $provider,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{prov_siren}", name="provider_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Provider $provider): Response
    {
        if ($this->isCsrfTokenValid('delete'.$provider->getProv_siren(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($provider);
            $entityManager->flush();
        }

        return $this->redirectToRoute('provider_index');
    }
}

templates/provider/_delete_form.html.twig
<form method="post" action="{{ path('provider_delete', {'prov_siren': provider.prov_siren}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ provider.prov_siren) }}">
    <button class="btn">Delete</button>
</form>

templates/provider/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/provider/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Provider{% endblock %}

{% block body %}
    <h1>Edit Provider</h1>

    {{ include('provider/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('provider_index') }}">back to list</a>

    {{ include('provider/_delete_form.html.twig') }}
{% endblock %}

templates/provider/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Provider index{% endblock %}

{% block body %}
    <h1>Liste des fournisseurs</h1>

    <table class="table">
        <thead>
            <tr>
                <th>SIREN</th>
                <th>Nom</th>
                <th>Adresse mail</th>
                <th>Téléphone</th>
                <th>Description</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for provider in providers %}
            <tr>
                <td>{{ provider.provSiren }}</td>
                <td>{{ provider.provName }}</td>
                <td>{{ provider.provMail }}</td>
                <td>{{ provider.provPhone }}</td>
                <td>{{ provider.provDescr }}</td>
                <td>
                    <a href="{{ path('provider_show', {'prov_siren': provider.prov_siren}) }}"><i class="fas fa-eye"></i></a>&nbsp;&nbsp;
                    <a href="{{ path('provider_edit', {'prov_siren': provider.prov_siren}) }}"><i class="fas fa-edit"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('provider_new') }}">Create new</a>
{% endblock %}

templates/provider/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Provider{% endblock %}

{% block body %}
    <h1>Create new Provider</h1>

    {{ include('provider/_form.html.twig') }}

    <a href="{{ path('provider_index') }}">back to list</a>
{% endblock %}

templates/provider/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Provider{% endblock %}

{% block body %}
    <h1>Provider</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Prov_siren</th>
                <td>{{ provider.provSiren }}</td>
            </tr>
            <tr>
                <th>Prov_name</th>
                <td>{{ provider.provName }}</td>
            </tr>
            <tr>
                <th>Prov_mail</th>
                <td>{{ provider.provMail }}</td>
            </tr>
            <tr>
                <th>Prov_phone</th>
                <td>{{ provider.provPhone }}</td>
            </tr>
            <tr>
                <th>Prov_descr</th>
                <td>{{ provider.provDescr }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('provider_index') }}">back to list</a>

    <a href="{{ path('provider_edit', {'prov_siren': provider.prov_siren}) }}">edit</a>

    {{ include('provider/_delete_form.html.twig') }}
{% endblock %}